-- MySQL Script generated by MySQL Workbench
-- Tue May 15 10:38:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema itraining
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema itraining
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itraining` DEFAULT CHARACTER SET utf8 ;
USE `itraining` ;

-- -----------------------------------------------------
-- Table `itraining`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`member` (
  `wx_id` VARCHAR(32) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `name` VARCHAR(64) NULL,
  `bio` VARCHAR(256) NULL,
  PRIMARY KEY (`wx_id`),
  UNIQUE INDEX `wx_id_UNIQUE` (`wx_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`team` (
  `team_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `bio` VARCHAR(256) NULL,
  `leader_id` VARCHAR(32) NULL,
  `join_token` VARCHAR(256) NULL,
  PRIMARY KEY (`team_id`),
  INDEX `leader_id_idx` (`leader_id` ASC),
  CONSTRAINT `team_fk1`
    FOREIGN KEY (`leader_id`)
    REFERENCES `itraining`.`member` (`wx_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`join_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`join_info` (
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `wx_id` VARCHAR(32) NOT NULL,
  `team_id` INT UNSIGNED NOT NULL,
  INDEX `wx_id_idx` (`wx_id` ASC),
  INDEX `team_id_idx` (`team_id` ASC),
  CONSTRAINT `request_fk1`
    FOREIGN KEY (`wx_id`)
    REFERENCES `itraining`.`member` (`wx_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `request_fk2`
    FOREIGN KEY (`team_id`)
    REFERENCES `itraining`.`team` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`diary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`diary` (
  `diary_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(512) NULL,
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `wx_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`diary_id`),
  INDEX `wx_id_idx` (`wx_id` ASC),
  CONSTRAINT `diary_fk1`
    FOREIGN KEY (`wx_id`)
    REFERENCES `itraining`.`member` (`wx_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`schedule` (
  `schedule_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `class` VARCHAR(16) NOT NULL DEFAULT '平时训练',
  `wx_id` VARCHAR(32) NULL,
  `team_id` INT UNSIGNED NULL,
  PRIMARY KEY (`schedule_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`check` (
  `checked_date` TIMESTAMP NULL,
  `checked` VARCHAR(32) NOT NULL DEFAULT '未完成',
  `wx_id` VARCHAR(32) NULL,
  `schedule_id` INT NULL,
  INDEX `wx_id_idx` (`wx_id` ASC),
  INDEX `schedule_id_idx` (`schedule_id` ASC),
  CONSTRAINT `check_fk1`
    FOREIGN KEY (`wx_id`)
    REFERENCES `itraining`.`member` (`wx_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `check_fk2`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `itraining`.`schedule` (`schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`training_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`training_meta` (
  `training_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `traiing_name` VARCHAR(64) NULL,
  `index1` VARCHAR(64) NULL,
  `index2` VARCHAR(64) NULL,
  `index3` VARCHAR(64) NULL,
  `index4` VARCHAR(64) NULL,
  PRIMARY KEY (`training_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`training_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`training_record` (
  `record_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_number` INT UNSIGNED NULL,
  `data1` FLOAT NOT NULL DEFAULT 0.0,
  `data2` FLOAT NOT NULL DEFAULT 0.0,
  `data3` FLOAT NOT NULL DEFAULT 0.0,
  `data4` FLOAT NOT NULL DEFAULT 0.0,
  `class` VARCHAR(16) NOT NULL DEFAULT '平时训练',
  `schedule_id` INT UNSIGNED NULL,
  `training_id` INT UNSIGNED NULL,
  `wx_id` VARCHAR(32) NULL,
  `diary_id` INT UNSIGNED NULL,
  PRIMARY KEY (`record_id`),
  INDEX `schedule_id_idx` (`schedule_id` ASC),
  INDEX `training_id_idx` (`training_id` ASC),
  INDEX `wx_id_idx` (`wx_id` ASC),
  INDEX `diary_id_idx` (`diary_id` ASC),
  CONSTRAINT `record_fk1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `itraining`.`schedule` (`schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `record_fk2`
    FOREIGN KEY (`training_id`)
    REFERENCES `itraining`.`training_meta` (`training_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `record_fk3`
    FOREIGN KEY (`wx_id`)
    REFERENCES `itraining`.`member` (`wx_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `record_fk4`
    FOREIGN KEY (`diary_id`)
    REFERENCES `itraining`.`diary` (`diary_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
