-- MySQL Script generated by MySQL Workbench
-- Sat Jun 30 15:34:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema itraining
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema itraining
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itraining` DEFAULT CHARACTER SET utf8 ;
USE `itraining` ;

-- -----------------------------------------------------
-- Table `itraining`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`user` (
  `wx_id` VARCHAR(32) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `nickname` VARCHAR(64) NULL,
  `bio` VARCHAR(256) NULL,
  `image_url` VARCHAR(256) NULL,
  PRIMARY KEY (`wx_id`),
  UNIQUE INDEX `wx_id_UNIQUE` (`wx_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`team` (
  `team_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `bio` VARCHAR(256) NULL,
  `leader_id` VARCHAR(32) NULL,
  `join_token` VARCHAR(256) NULL,
  `image_url` VARCHAR(256) NULL,
  PRIMARY KEY (`team_id`),
  INDEX `leader_id_idx` (`leader_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `team_fk1`
    FOREIGN KEY (`leader_id`)
    REFERENCES `itraining`.`user` (`wx_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`join_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`join_info` (
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `wx_id` VARCHAR(32) NOT NULL,
  `team_id` INT UNSIGNED NOT NULL,
  INDEX `wx_id_idx` (`wx_id` ASC),
  INDEX `team_id_idx` (`team_id` ASC),
  UNIQUE INDEX `wx_team_unique` (`wx_id` ASC, `team_id` ASC),
  CONSTRAINT `request_fk1`
    FOREIGN KEY (`wx_id`)
    REFERENCES `itraining`.`user` (`wx_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `request_fk2`
    FOREIGN KEY (`team_id`)
    REFERENCES `itraining`.`team` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`diary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`diary` (
  `diary_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(512) NULL,
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `wx_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`diary_id`),
  INDEX `wx_id_idx` (`wx_id` ASC),
  CONSTRAINT `diary_fk1`
    FOREIGN KEY (`wx_id`)
    REFERENCES `itraining`.`user` (`wx_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`schedule` (
  `schedule_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `training_class` VARCHAR(16) NOT NULL DEFAULT '训练',
  `wx_id` VARCHAR(32) NULL,
  `team_id` INT UNSIGNED NULL DEFAULT NULL,
  `description` VARCHAR(512) NULL,
  `title` VARCHAR(64) NULL,
  `training_date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `state` VARCHAR(45) NOT NULL DEFAULT '草稿',
  PRIMARY KEY (`schedule_id`),
  INDEX `schedule_fk1_idx` (`team_id` ASC),
  CONSTRAINT `schedule_fk1`
    FOREIGN KEY (`team_id`)
    REFERENCES `itraining`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`training_punch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`training_punch` (
  `punch_date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `completion` INT NOT NULL DEFAULT 100,
  `wx_id` VARCHAR(32) NOT NULL,
  `schedule_id` INT UNSIGNED NOT NULL,
  `description` VARCHAR(512) NULL,
  `image_url` VARCHAR(256) NULL,
  `punch_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `wx_id_idx` (`wx_id` ASC),
  INDEX `schedule_id_idx` (`schedule_id` ASC),
  UNIQUE INDEX `wx_schedule_unique` (`wx_id` ASC, `schedule_id` ASC),
  PRIMARY KEY (`punch_id`),
  CONSTRAINT `check_fk1`
    FOREIGN KEY (`wx_id`)
    REFERENCES `itraining`.`user` (`wx_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `check_fk2`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `itraining`.`schedule` (`schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`training_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`training_meta` (
  `meta_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `training_name` VARCHAR(64) NULL,
  `index1` VARCHAR(64) NULL,
  `index2` VARCHAR(64) NULL,
  `index3` VARCHAR(64) NULL,
  `index4` VARCHAR(64) NULL,
  `index5` VARCHAR(64) NULL,
  `index6` VARCHAR(64) NULL,
  `team_id` INT UNSIGNED NULL,
  PRIMARY KEY (`meta_id`),
  INDEX `training_meta_fk1_idx` (`team_id` ASC),
  UNIQUE INDEX `unique_name` (`training_name` ASC, `team_id` ASC),
  CONSTRAINT `training_meta_fk1`
    FOREIGN KEY (`team_id`)
    REFERENCES `itraining`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`training_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`training_reference` (
  `reference_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_number` INT UNSIGNED NULL,
  `data1` FLOAT NOT NULL DEFAULT 0.0,
  `data2` FLOAT NOT NULL DEFAULT 0.0,
  `data3` FLOAT NOT NULL DEFAULT 0.0,
  `data4` FLOAT NOT NULL DEFAULT 0.0,
  `data5` FLOAT NOT NULL DEFAULT 0,
  `data6` FLOAT NOT NULL DEFAULT 0,
  `test_index` INT NOT NULL DEFAULT -1,
  `schedule_id` INT UNSIGNED NULL,
  `meta_id` INT UNSIGNED NULL,
  PRIMARY KEY (`reference_id`),
  INDEX `schedule_id_idx` (`schedule_id` ASC),
  INDEX `training_id_idx` (`meta_id` ASC),
  CONSTRAINT `reference_fk1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `itraining`.`schedule` (`schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `reference_fk2`
    FOREIGN KEY (`meta_id`)
    REFERENCES `itraining`.`training_meta` (`meta_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itraining`.`testing_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itraining`.`testing_record` (
  `record_id` INT NOT NULL AUTO_INCREMENT,
  `reference_id` INT UNSIGNED NOT NULL,
  `group_id` INT NOT NULL DEFAULT 0,
  `data` FLOAT NOT NULL DEFAULT 0,
  `date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `wx_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`record_id`),
  INDEX `record_fk1_idx` (`reference_id` ASC),
  INDEX `record_fk2_idx` (`wx_id` ASC),
  CONSTRAINT `record_fk1`
    FOREIGN KEY (`reference_id`)
    REFERENCES `itraining`.`training_reference` (`reference_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `record_fk2`
    FOREIGN KEY (`wx_id`)
    REFERENCES `itraining`.`user` (`wx_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
